# Generated by Django 3.0.2 on 2020-01-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200120_1331'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinet',
            name='a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
        ),
    ]
