# Generated by Django 3.0.2 on 2020-01-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercabinet_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercabinet',
            name='a',
        ),
    ]
