# Generated by Django 3.0.2 on 2020-01-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200120_1331'),
        ('users', '0004_auto_20200120_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Categories')),
                ('user_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserCabinet')),
            ],
        ),
        migrations.RemoveField(
            model_name='usercabinet',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='subscriptions',
            field=models.ManyToManyField(through='users.SendMails', to='main_app.Categories'),
        )
    ]
